.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

stages:
  - format-check
  - lint
  - test
  - build

format-check-job:
  rules:
    - !reference [.default_rules, rules]
  stage: format-check
  tags:
    - docker
    - shared
  image: node:23-alpine
  script:
    - echo "Running prettier format check... This may take a while."
    - yarn install
    - yarn workspace @gamepark/popcorn run prettier --check **/*.{js,ts,tsx}
    - yarn workspace @gamepark/popcorn-app run prettier --check **/*.{js,ts,tsx}


lint-job:
  rules:
    - !reference [.default_rules, rules]
  stage: lint
  tags:
    - docker
    - shared
  image: node:23-alpine
  script:
    - echo "Running linter... This may take a while."
    - yarn install
    - yarn run lint

test-job:
  rules:
    - !reference [.default_rules, rules]
  stage: test
  tags:
    - docker
    - shared
  image: node:23-alpine
  script:
    - echo "Running tests... This may take a while."
    - yarn install
    - yarn workspace @gamepark/popcorn test

build:
  rules:
    - !reference [.default_rules, rules]
  stage: build
  tags:
    - docker
    - shared
  image: node:23-alpine
  script:
    - echo "Build app and rules... This may take a while."
    - yarn install
    - yarn workspace @gamepark/popcorn run build
    - yarn workspace @gamepark/popcorn-app run build
